### PR TITLE
Cdb 2.5.x

### PR DESCRIPTION
**Pull request by rafatower**
This branch consist of current upstream master `v2.5.1` plus our changes from current branch `cdb-2.x` (version `2.3.1-cdb4 `) rebased onto it.

It was built like this:
```
git fetch --all
git checkout cdb-2.x
git checkout -b cdb-2.5.x
git rebase v2.5.1
# solve conflicts
# mainly with git mergetool -t kdiff3
# and then git --continue
git push -u carto HEAD
```

I had to solve manually a number of conflicts, but they were fairly simple to solve to trust the process.

If this works properly, I'll modify it to point to our dependencies and then merge (it should then merge cleanly) into our `cdb-2.x` branch.

### CODE REVIEW

**Comment by rafatower** [comment]
@dgaubert I think I'm pretty much done with this. Can you please review it?

There are two ways of seeing the changes:
- just the diff against `cdb-2.x`
- diffing against upstream `origin/master`

Personally, I find easier the later one. Another way is checking the individual commits (I tried to keep mine clean)

It complains about conflicts. If we're ok with the changes then the way of solving them is simply give priority to this branch over `cdb-2.x`.

**Review by dgaubert — APPROVED** [review]
LGTM

If there is no problem by using `npm` I'd remove `yarn.lock` since we use `npm` everywhere but `windshaft-cartodb`.

Great having a separated CHANGELOG.

:shipit:

**Comment by rafatower** [comment]
Re yarn and npm: with our current packaging, our `@carto/mapnik` cannot be installed using npm:
```
$ npm --version
3.10.9
$ mkdir /tmp/test-mapnik
$ cd /tmp/test-mapnik/
$ npm init -y
$ npm install @carto/mapnik
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason
test-mapnik@1.0.0 /tmp/test-mapnik
├── mapnik-vector-tile@1.5.0  extraneous
├── nan@2.7.0  extraneous
└── protozero@1.5.1  extraneous

npm WARN test-mapnik@1.0.0 No description
npm WARN test-mapnik@1.0.0 No repository field.
npm ERR! Linux 4.10.0-42-generic
npm ERR! argv "/home/rtorre/.nvm/versions/node/v6.9.2/bin/node" "/home/rtorre/.nvm/versions/node/v6.9.2/bin/npm" "install" "@carto/mapnik"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path /tmp/test-mapnik/node_modules/.staging/abbrev-06389b2b
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/tmp/test-mapnik/node_modules/.staging/abbrev-06389b2b' -> '/tmp/test-mapnik/node_modules/@carto/mapnik/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/tmp/test-mapnik/node_modules/.staging/abbrev-06389b2b' -> '/tmp/test-mapnik/node_modules/@carto/mapnik/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/test-mapnik/npm-debug.log
```

but with a newer version:
```
$ nvm use v8.9.4
Now using node v8.9.4 (npm v5.6.0)
$ npm --version
5.6.0
$ npm install @carto/mapnik                                                                                                                                                                                                                                                                

> @carto/mapnik@3.6.2-carto.1 install /tmp/test-mapnik/node_modules/@carto/mapnik
> node-pre-gyp install --fallback-to-build

[@carto/mapnik] Success: "/tmp/test-mapnik/node_modules/@carto/mapnik/lib/binding/mapnik.node" is installed via remote
npm WARN test-mapnik@1.0.0 No description
npm WARN test-mapnik@1.0.0 No repository field.

+ @carto/mapnik@3.6.2-carto.1
added 117 packages in 18.775s
```

Let us know if you think that could be a problem and would require further investigation. From my perspective, the `yarn.lock` should only be used for testing.

**Comment by dgaubert** [comment]
> Let us know if you think that could be a problem and would require further investigation. From my perspective, the yarn.lock should only be used for testing.

It's not a problem, we deploy tiler with `yarn` but I'm afraid that we are more and more dependent on `yarn` which is not the best scenario because so far `tiler` was the exception.

Anyway, let's go ahead.

**Pull request merged**
